export const PROGRAM_LIST_REQUEST = "PROGRAM_LIST_REQUEST";
export const PROGRAM_LIST_SUCCESS = "PROGRAM_LIST_SUCCESS";
export const PROGRAM_LIST_FAIL = "PROGRAM_LIST_FAIL";

export const PROGRAM_DETAIL_REQUEST = "PROGRAM_DETAIL_REQUEST";
export const PROGRAM_DETAIL_SUCCESS = "PROGRAM_DETAIL_SUCCESS";
export const PROGRAM_DETAIL_FAIL = "PROGRAM_DETAIL_FAIL";

export const PROGRAM_SEARCH_REQUEST = "PROGRAM_SEARCH_REQUEST";
export const PROGRAM_SEARCH_SUCCESS = "PROGRAM_SEARCH_SUCCESS";
export const PROGRAM_SEARCH_FAIL = "PROGRAM_SEARCH_FAIL";